# Copyright (C) 2014 Google Inc., authors, and contributors <see AUTHORS file>
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
# Created By: goran@reciprocitylabs.com
# Maintained By: goran@reciprocitylabs.com

---
- name: install requirements
  sudo: yes
  pip:
    requirements: "/vagrant/src/requirements.txt"

- name: install packages
  sudo: yes
  with_items: ggrc_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: create development directories
  sudo: yes
  with_items: ggrc_development_directories
  file:
    path: "{{ item.name }}"
    owner: vagrant
    group: vagrant
    state: directory

- name: prepare development virtualenv
  command: make setup_dev DEV_PREFIX=/vagrant-dev
  args:
    chdir: /vagrant

- name: remove gems
  sudo: yes
  shell: gem list | cut -d " " -f1 | xargs gem uninstall -aIx 2> /dev/null || true

- name: install gems
  sudo: yes
  with_items: ggrc_gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: no
    state: present

- name: install global npm modules
  sudo: yes
  with_items: ggrc_global_npm_modules
  npm:
    name: "{{ item.name }}"
    global: yes
    state: present
    registry: http://registry.npmjs.org/

- name: install local npm modules
  sudo: no
  with_items: ggrc_local_npm_modules
  npm:
    name: "{{ item.name }}"
    state: present
    registry: http://registry.npmjs.org/
    path: "/vagrant/node_modules"

- name: run make appengine
  command: make appengine DEV_PREFIX=/vagrant-dev
  args:
    chdir: /vagrant

- name: run make bower_components
  command: make bower_components
  args:
    chdir: /vagrant

- name: change root password
  mysql_user:
    name: root
    password: root
    login_user: root
    login_password: root
    check_implicit_admin: yes
    priv: "*.*:ALL"

- name: create databases
  with_items: ggrc_databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
    login_user: root
    login_password: root

- name: configure bash
  sudo: yes
  template:
    src: .bashrc.j2
    dest: /home/vagrant/.bashrc
    owner: vagrant
    group: vagrant
